# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
# 日志配置
logging:
  level:
    com.coffee.kafeisummary: debug
    org.springframework: warn

# Spring配置
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  # 模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    # 禁用缓存
    cache: false
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
  # 资源信息
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
# MyBatis
mybatis:
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
  # 搜索指定包别名
  typeAliasesPackage: com.coffee.kafeisummary.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml